name: The name of your action here
description: Provide a description here
author: Your name or organization here

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: heart
  color: red

# Define your inputs here.
inputs:
  url:
    description: Dev Center URL to use
    default: 'https://dev-center.flake.gg'
  api-key:
    description: Dev Center API key to use
    required: true
  github-token:
    description: 'GitHub token for API access'
    default: ${{ github.token }}


# Define your outputs here.
#outputs:

runs:
  using: node24
  main: dist/index.js
